apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: | 
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFHVm9aV2hsSUM0dUxpQk9ZVzhnWm05cElHUmxjM05oSUhabGVpQXVMaTRnVkdWdWRHVWdibUVnY0hKdmVHbHRZUT09IgoJCX0KCX0KfQo=