apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: desafio-nginx-volume-deployment
  name: desafio-nginx-volume-deployment
  namespace: treinamento-ch2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-volume
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: desafio-volume
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 128Mi
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 7
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 4
          successThreshold: 2
        volumeMounts:
        - name: meu-pvc
          mountPath: /usr/share/nginx/html
      volumes:
      - name: meu-pvc
        persistentVolumeClaim:
          claimName: meu-pvc