apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-multicontainers
    serverType: webserver
    tool: nginx
    os: ubuntu
  name: pod-multicontainers
spec:
  containers:
  - name: webserver-nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "300Mi"
        cpu: "0.5" 
      requests:
        memory: "100Mi"
        cpu: "0.2"
    volumeMounts:
    - name: volume-webserver
      mountPath: /usr/share/nginx/html
  - name: server-linux01
    image: ubuntu
    args:
    - sleep
    - infinity 
    resources:
      limits:
        memory: "500Mi"
        cpu: "0.5"
      requests:
        memory: "300Mi"
        cpu: "0.3"
    volumeMounts:
    - name: volume-linux
      mountPath: /emptydir-linux
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: volume-webserver
    emptyDir:
      sizeLimit: 50Mi
  - name: volume-linux
    emptyDir:
      sizeLimit: 50Mi
